import i18n from './index'

const ar = {
  'Jeddah Construction Portfolio':'محفظة مشاريع جدة الإنشائية','A real-time executive view of portfolio delivery, financial exposure and project health.':'عرض تنفيذي مباشر لتسليم المحفظة والتعرض المالي وصحة المشاريع.',
  'Projects by status':'المشاريع حسب الحالة','Project health distribution':'توزيع صحة المشاريع','Projects by sector':'المشاريع حسب القطاع','Completion distribution':'توزيع نسب الإنجاز','Budget by sector':'الميزانية حسب القطاع','Top projects requiring attention':'أبرز المشاريع التي تتطلب متابعة',
  'Delivery intelligence':'ذكاء التنفيذ','Schedule & Progress Performance':'أداء الجدول الزمني والتقدم','Understand variance early, isolate delays and track recovery across the portfolio.':'فهم الانحرافات مبكرًا وعزل التأخيرات ومتابعة التعافي في المحفظة.',
  'On track':'ضمن الجدول','Ahead of schedule':'متقدم عن الجدول','Critical delay':'تأخير حرج','Avg. schedule variance':'متوسط انحراف الجدول','Average delay days':'متوسط أيام التأخير','Planned vs actual progress':'المخطط مقابل الإنجاز الفعلي','Planned vs actual scatter':'مقارنة الإنجاز المخطط والفعلي','Schedule status distribution':'توزيع حالة الجدول','Progress trend':'اتجاه التقدم','Most delayed projects':'أكثر المشاريع تأخرًا',
  'Schedule recovery indicators':'مؤشرات تعافي الجدول','Projects on track':'مشاريع ضمن الجدول','Projects on hold':'مشاريع متوقفة','Risk command center':'مركز إدارة المخاطر',
  'Financial governance':'الحوكمة المالية','Budget & Financial Performance':'أداء الميزانية والتمويل','Monitor utilization, cash exposure and the relationship between spend and physical delivery.':'متابعة الاستغلال والتعرض النقدي والعلاقة بين الصرف والتنفيذ الفعلي.','Total contract value':'إجمالي قيمة العقود','Approved budget':'الميزانية المعتمدة','Amount spent':'المبلغ المصروف','Remaining budget':'الميزانية المتبقية','Budget utilization':'استخدام الميزانية','Over budget':'تجاوزت الميزانية','Under watch':'تحت المراقبة','Budget vs spent by sector':'الميزانية والصرف حسب القطاع','Financial vs physical progress':'التقدم المالي مقابل الفعلي','Top projects by contract value':'أعلى المشاريع قيمة بالعقود','Monthly spending trend':'اتجاه الإنفاق الشهري','Financial risk projects':'مشاريع المخاطر المالية',
  'Partner ecosystem':'منظومة الشركاء','Contractor Performance':'أداء المقاولين','Compare delivery strength, portfolio exposure and recovery needs across delivery partners.':'مقارنة قوة التنفيذ والتعرض المالي واحتياج التعافي لدى شركاء التنفيذ.','Total contractors':'إجمالي المقاولين','Projects assigned':'المشاريع المسندة','Portfolio value':'قيمة المحفظة','Average progress':'متوسط الإنجاز','With delayed projects':'لديهم مشاريع متأخرة','Contract value by contractor':'قيمة العقود حسب المقاول','Contractor portfolio':'محفظة المقاولين','Average progress by contractor':'متوسط الإنجاز حسب المقاول','Contractor ranking':'ترتيب المقاولين',
  'Spatial portfolio view':'العرض المكاني للمحفظة','Geographic Project Map':'الخريطة الجغرافية للمشاريع','Explore active delivery across Jeddah districts and select a project to locate it precisely.':'استكشف التنفيذ النشط في أحياء جدة واختر مشروعًا لتحديد موقعه بدقة.','Live project locations':'مواقع المشاريع المباشرة','Projects on map':'المشاريع على الخريطة','Select a project to focus the map on its district.':'اختر مشروعًا للتركيز على موقعه في الخريطة.',
  'Project':'المشروع','Contractor':'المقاول','Progress':'الإنجاز','Variance':'الانحراف','Delay':'التأخير','Health':'الصحة','Budget':'الميزانية','Spent':'المصروف','Budget status':'حالة الميزانية','Rank':'الترتيب','Projects':'المشاريع','Completed':'مكتمل','Delayed':'متأخر','Total value':'إجمالي القيمة','Avg. progress':'متوسط الإنجاز','Avg. delay':'متوسط التأخير','Performance':'الأداء','All':'الكل','Reset filters':'إعادة ضبط الفلاتر','Sector':'القطاع','Status':'الحالة','District':'الحي','Priority':'الأولوية','Project manager':'مدير المشروع','Contract value':'قيمة العقد','Financial progress':'التقدم المالي','Planned start':'البداية المخططة','Actual start':'البداية الفعلية','Planned end':'النهاية المخططة','Expected end':'النهاية المتوقعة','Planned progress':'التقدم المخطط','Schedule variance':'انحراف الجدول','Budget variance':'انحراف الميزانية','Delay days':'أيام التأخير','Risk':'المخاطر','Health score':'درجة الصحة','Actual progress':'الإنجاز الفعلي','Notifications':'التنبيهات','Critical schedule exposure':'مخاطر حرجة في الجدول','Financial watch list':'قائمة مراقبة مالية','Portfolio refresh complete':'اكتمل تحديث المحفظة','new':'جديدة','View project details':'عرض تفاصيل المشروع',
  'Contractor Name':'اسم المقاول','Project Manager Name':'اسم مدير المشروع','Project ID':'معرف المشروع','Projects on hold':'مشاريع متوقفة','Project alerts':'تنبيهات المشاريع','Financial exposure':'التعرض المالي','Risk projects':'مشاريع المخاطر','Contractor reliability score':'مؤشر موثوقية المقاول','Physical delivery balance':'توازن التنفيذ الفعلي','Financial delivery balance':'توازن الأداء المالي',
  'Healthy':'سليم','Monitor':'تحت المراقبة','At Risk':'معرض للخطر','Critical':'حرج','Low':'منخفض','Medium':'متوسط','High':'مرتفع','Strategic':'استراتيجي','Not Started':'لم يبدأ','In Progress':'قيد التنفيذ','On Hold':'متوقف','Ahead of Schedule':'متقدم عن الجدول','On Track':'ضمن الجدول','Slightly Delayed':'تأخير طفيف','Critical Delay':'تأخير حرج','Under Budget':'ضمن الميزانية','On Budget':'متوافق مع الميزانية','Watch':'تحت المراقبة','Over Budget':'تجاوز الميزانية','Excellent':'ممتاز','Good':'جيد','Needs Attention':'يحتاج متابعة','Poor':'ضعيف',
  'Roads & Transportation':'الطرق والنقل','Buildings':'المباني','Stormwater & Drainage':'تصريف مياه الأمطار','Parks & Landscaping':'الحدائق والتشجير','Utilities':'المرافق','Street Lighting':'إنارة الشوارع','Public Facilities':'المرافق العامة','Urban Development':'التطوير الحضري'
}
const terms = {
  'Al Binaa Contracting Co.':'شركة البناء للمقاولات','Nesma Urban Contracting':'نسما للمقاولات الحضرية','Blue Horizon Contractors':'مقاولو الأفق الأزرق','Western Projects Company':'شركة المشاريع الغربية','First Route Engineering':'هندسة المسار الأول','Jeddah Urban Works Co.':'شركة أعمال جدة الحضرية','Gulf Engineering & Construction':'الخليج للهندسة والإنشاءات','Arabian Development Contractors':'مقاولو التنمية العربية','Future Cities Construction':'إنشاءات مدن المستقبل','Saudi Infrastructure Solutions':'حلول البنية التحتية السعودية','Red Sea Infrastructure Ltd.':'البحر الأحمر للبنية التحتية','Horizon Construction Group':'مجموعة الأفق للإنشاءات','Al Manar Contracting':'مقاولات المنار','Corniche Civil Works':'أعمال كورنيش المدنية','Madar Utilities & Build':'مدار للمرافق والبناء','Desert Line Projects':'مشاريع خط الصحراء','Alpha Core Construction':'إنشاءات ألفا كور','Nesma Urban Contracting':'نسما للمقاولات الحضرية','Vision Axis Developments':'تطوير محور الرؤية','Prime Gulf Builders':'بناة الخليج المتميزون','Modern Grid Contracting':'مقاولات الشبكة الحديثة',
  'Al Hamdaniyah':'الحمدانية','Al Muhammadiyah':'المحمدية','Al Baghdadiyah':'البغدادية','Al Khalidiyah':'الخالدية','Al Faisaliyah':'الفيصلية','Al Aziziyah':'العزيزية','Al Salamah':'السلامة','Al Rawdah':'الروضة','Al Rawabi':'الروابي','Al Andalus':'الأندلس','Al Basateen':'البساتين','Al Kandarah':'الكندرة','Al Sanabel':'السنابل','Al Rowais':'الرويس','Al Ruwais':'الرويس','Al Rahab':'الرحاب','Al Rehab':'الرحاب','Al Marwah':'المروة','Al Naseem':'النسيم','Al Naeem':'النعيم','Al Bawadi':'البوادي','Al Hamra':'الحمراء','Al Shati':'الشاطئ','Al Thaghr':'الثغر','Al Jamiah':'الجامعة','Al Rabwah':'الربوة','Al Samer':'السامر','Al Ajwad':'الأجواد','Al Manar':'المنار','Al Waha':'الواحة','Al Zahra':'الزهراء','Al Safa':'الصفا','Al Balad':'البلد','Obhur':'أبحر','Prince Fawaz':'الأمير فواز',
  'Northern Jeddah':'شمال جدة','Southern Jeddah':'جنوب جدة','Eastern Jeddah':'شرق جدة','Western Jeddah':'غرب جدة','Central Jeddah':'وسط جدة','Haramain Gateway':'بوابة الحرمين','Airport District':'حي المطار','King Abdulaziz Road':'طريق الملك عبدالعزيز','Prince Majed Corridor':'محور الأمير ماجد','Corniche':'الكورنيش','Traffic Flow Optimization':'تحسين انسيابية الحركة','Corridor Enhancement':'تحسين المحور','Intersection Upgrade':'تطوير التقاطع','Street Lighting Upgrade':'تطوير إنارة الشوارع','Mixed-Use Infrastructure Development':'تطوير البنية التحتية متعددة الاستخدامات','Municipal Building Renovation':'تجديد المبنى البلدي','Service Center Upgrade':'تطوير مركز الخدمة','Bridge Rehabilitation':'تأهيل الجسر','Transport Link Upgrade':'تطوير وصلة النقل','Public Realm Improvement':'تحسين المجال العام','Water Channel Rehabilitation':'تأهيل قناة المياه','Drainage Network Expansion':'توسعة شبكة التصريف','Stormwater Drainage Upgrade':'تطوير تصريف مياه الأمطار','Public Building Rehabilitation':'تأهيل المبنى العام','Administrative Complex Development':'تطوير المجمع الإداري','Neighborhood Services Improvement':'تحسين خدمات الحي','Boulevard Landscaping Project':'مشروع تنسيق الطريق','Distribution Network Enhancement':'تحسين شبكة التوزيع','Operations Facility Expansion':'توسعة منشأة العمليات','Mobility Improvement':'تحسين الحركة','Waterfront Enhancement':'تحسين الواجهة البحرية','Runoff Management Improvement':'تحسين إدارة الجريان السطحي','Water & Sewer Infrastructure Renewal':'تجديد بنية المياه والصرف'
}
const alertAr = { 'Risk command center':'مركز إدارة المخاطر', 'Back to notifications':'العودة إلى التنبيهات', 'Projects requiring immediate action':'مشاريع تتطلب إجراءً فوريًا', 'Review each project below, understand its issue, and open its complete details.':'راجع كل مشروع أدناه، وتعرّف على مشكلته، ثم افتح تفاصيله الكاملة.', 'Reason for review':'سبب المراجعة', 'Open project details':'فتح تفاصيل المشروع', 'Projects with critical health require an immediate recovery plan and executive review.':'المشاريع ذات الحالة الحرجة تتطلب خطة تعافٍ فورية ومراجعة تنفيذية.', 'Projects where spending has exceeded the expected delivery position or approved budget.':'مشاريع تجاوز فيها الصرف مستوى التنفيذ المتوقع أو الميزانية المعتمدة.', 'Projects awaiting approval, coordination, or resolution of a delivery blocker.':'مشاريع بانتظار اعتماد أو تنسيق أو معالجة عائق تنفيذي.', 'Decisions and risks requiring immediate follow-up across the project portfolio.':'القرارات والمخاطر التي تحتاج إلى متابعة فورية في محفظة المشاريع.', 'Critical projects':'مشاريع حرجة', 'Financial risks':'مخاطر مالية', 'High delays or declining project health require a clear recovery plan.':'تأخيرات عالية أو انخفاض في صحة المشروع تتطلب خطة معالجة واضحة.', 'Spending is ahead of physical progress or exceeds the approved budget.':'الصرف أعلى من التقدم الفعلي أو يتجاوز الميزانية المعتمدة.', 'Open critical projects':'فتح المشاريع الحرجة', 'Open financial risks':'فتح قائمة المخاطر', 'Open projects on hold':'فتح المشاريع المتوقفة', 'critical projects require review':'مشاريع حرجة تتطلب مراجعة', 'projects are above expected spend':'مشاريع أعلى من مستوى الصرف المتوقع', 'Local PMO dataset updated 03 Sep 2026':'تم تحديث بيانات مكتب إدارة المشاريع المحلية في 03 سبتمبر 2026' }
const managerAr = { 'Abdullah Alzahrani':'عبدالله الزهراني', 'Ahmed Alharbi':'أحمد الحربي', 'Bander Alghamdi':'بندر الغامدي', 'Fahad Alghamdi':'فهد الغامدي', 'Hassan Alzahrani':'حسن الزهراني', 'Khalid Alotaibi':'خالد العتيبي', 'Majed Alharbi':'ماجد الحربي', 'Mohammed Alqahtani':'محمد القحطاني', 'Nawaf Alqahtani':'نواف القحطاني', 'Omar Alshehri':'عمر الشهري', 'Saad Alshammari':'سعد الشمري', 'Tariq Alotaibi':'طارق العتيبي', 'Turki Almutairi':'تركي المطيري', 'Yousef Alsubaie':'يوسف السبيعي' }
const noteAr = { 'Contractor submitted recovery plan.':'قدّم المقاول خطة التعافي.' }
export const localize = (value) => { if (i18n.language !== 'ar' || typeof value !== 'string') return value; if (ar[value] || alertAr[value] || managerAr[value] || noteAr[value]) return ar[value] || alertAr[value] || managerAr[value] || noteAr[value]; return Object.entries({...terms,...alertAr,...managerAr,...noteAr}).sort(([a],[b])=>b.length-a.length).reduce((text,[from,to])=>text.replaceAll(from,to),value) }
export const projectCount = (value) => i18n.language === 'ar' ? `${value} مشروعًا` : `${value} projects`
