import { useState } from 'react'
import { MapContainer, TileLayer, CircleMarker, Popup, useMap } from 'react-leaflet'
import { Crosshair } from 'lucide-react'
import { ChartCard, Badge } from '../components/UI'
import { currency, percent } from '../utils/formatters'
import { projectMapDistrict, projectMapLocation } from '../data/service'
import { localize } from '../i18n/labels'

const tone = p => p.Status==='On Hold' ? '#8c96a4' : p.Health_Status==='Critical'||p.Status==='Delayed' ? '#e46159' : p.Health_Status==='Monitor'||p.Health_Status==='At Risk' ? '#e3a839' : '#1ca98a'
function FlyToProject({ project }) { const map=useMap(); if (project) { const [lat,lng]=projectMapLocation(project); map.flyTo([lat,lng], 14, {duration:.8}) } return null }
export default function ProjectMap({projects,onProject}) { const [focused,setFocused]=useState(null); const list=[...projects].sort((a,b)=>a.Project_Health_Score-b.Project_Health_Score).slice(0,9); const selectProject=project=>setFocused(project); return <><div className="page-intro"><span className="eyebrow">{localize('Spatial portfolio view')}</span><h1>{localize('Geographic Project Map')}</h1><p>{localize('Explore active delivery across Jeddah districts and select a project to locate it precisely.')}</p></div><div className="map-layout"><ChartCard title="Live project locations" className="map-panel"><MapContainer center={[21.54,39.18]} zoom={11} scrollWheelZoom className="leaflet-map"><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><FlyToProject project={focused}/>{projects.map(p=>{const [lat,lng]=projectMapLocation(p); return <CircleMarker key={p.Project_ID} center={[lat,lng]} radius={focused?.Project_ID===p.Project_ID?10:7} eventHandlers={{click:()=>selectProject(p)}} pathOptions={{color:tone(p),fillColor:tone(p),fillOpacity:.86,weight:focused?.Project_ID===p.Project_ID?4:2}}><Popup><div className="map-popup"><b>{localize(p.Project_Name)}</b><span>{localize(p.Contractor_Name)}</span><span>{localize(p.Sector)} · {localize(projectMapDistrict(p))}</span><strong>{currency(p.Contract_Value)}</strong><span>{percent(p.Actual_Progress)} complete · {p.Delay_Days} delay days</span><Badge value={p.Health_Status}/><button onClick={()=>onProject(p)}>{localize('View project details')}</button></div></Popup></CircleMarker>})}</MapContainer></ChartCard><aside className="district-panel panel map-project-list"><h3>{localize('Projects on map')}</h3><p>{localize('Select a project to focus the map on its district.')}</p>{list.map((project,index)=><button className={focused?.Project_ID===project.Project_ID?'selected':''} onClick={()=>selectProject(project)} key={project.Project_ID}><span>{String(index+1).padStart(2,'0')}</span><div><b>{localize(project.Project_Name)}</b><small>{localize(projectMapDistrict(project))} · {percent(project.Actual_Progress)}</small></div><Crosshair size={15}/></button>)}<div className="map-legend"><span><i className="dot healthy"/>{localize('Healthy')} / {localize('Completed')}</span><span><i className="dot monitor"/>{localize('Monitor')} / {localize('At Risk')}</span><span><i className="dot critical"/>{localize('Delayed')} / {localize('Critical')}</span><span><i className="dot hold"/>{localize('On Hold')}</span></div></aside></div></> }
